{{- if .Values.recordCreationDetails.enabled -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: record-creation-details
  annotations:
    policies.kyverno.io/title: Record Creation Details
    policies.kyverno.io/category: other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Annotation
    policies.kyverno.io/description: >-
      Kubernetes by default does not make a record of who or what
      created a resource in that resource itself. It must be retrieved from
      an audit log, if enabled, which can make it difficult for cluster
      operators to know who was responsible for an object's creation.
      This policy writes an annotation with the key `kyverno.io/created-by`
      having all the userInfo fields present in the AdmissionReview request
      for any object being created. It then protects this annotation from
      tampering or removal making it immutable.      
spec:
  background: false
  rules:
  - name: add-userinfo
    match:
      any:
      - resources:
          kinds:
          - '*'
    preconditions:
      any:
      - key: "{{ "{{" }}request.operation{{ "}}" }}"
        operator: Equals
        value: CREATE
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            kyverno.io/created-by: "{{ "{{" }} request.userInfo | to_string(@) {{ "}}" }}"
{{- end }}