{{- if .Values.kyvernoPolicies.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: {{ .Values.argoCD.project }}
  source:
    chart: kyverno-policies
    repoURL: https://stuxcd.github.io/k8s-releases
    targetRevision: 1.0.0
    helm:
      releaseName: kyverno-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end -}}