name: Docker

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish debug-shed
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: josh9398/debug-shed
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: dockerfiles/debug-shed
