name: Docker

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish apline-curl
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: josh9398/alpine-curl
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: dockerfiles/alpine-curl
      - name: Publish s3fs
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: josh9398/s3fs
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: dockerfiles/s3fs
      - name: Publish debug-shed
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: josh9398/debug-shed
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: dockerfiles/debug-shed    
      - name: Publish wait-for-it
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: josh9398/wait-for-it
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: dockerfiles/debug-shed
